# Generated by Django 5.2.16 on 2026-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zaim_file', models.CharField(blank=True, max_length=200)),
                ('enavi_files', models.IntegerField(default=0)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_removed', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, help_text='小さいほど先に評価する')),
                ('pattern', models.CharField(help_text='正規化後の店名に対する正規表現', max_length=200)),
                ('merchant', models.CharField(help_text='表示に使う統一名', max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('kind', models.CharField(choices=[('サブスク', 'サブスク'), ('年会費', '年会費'), ('変動', '変動')], default='変動', max_length=10)),
                ('necessity', models.CharField(choices=[('必須', '必須'), ('準必須', '準必須'), ('裁量', '裁量'), ('要確認', '要確認')], default='要確認', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
                ('action', models.CharField(default='解約', help_text='解約 / 半減 / プラン変更 など', max_length=50)),
                ('annual_effect', models.IntegerField(help_text='年間効果額（円）')),
                ('status', models.CharField(choices=[('todo', '検討中'), ('doing', '実行中'), ('done', '完了'), ('skip', 'やらない')], db_index=True, default='todo', max_length=8)),
                ('decided_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-annual_effect', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('ym', models.CharField(db_index=True, max_length=7)),
                ('amount', models.IntegerField(help_text='円。負は値引き・ポイント利用・返金')),
                ('source_kind', models.CharField(choices=[('card', '楽天カード'), ('cash', '現金'), ('bank', '銀行'), ('unset', '支払元未設定')], db_index=True, max_length=8)),
                ('source_name', models.CharField(blank=True, max_length=50)),
                ('shop', models.CharField(blank=True, max_length=200)),
                ('shop_norm', models.CharField(blank=True, db_index=True, max_length=200)),
                ('merchant', models.CharField(blank=True, db_index=True, max_length=100)),
                ('label', models.CharField(blank=True, help_text='表示名（メモ→品目→店名の優先）', max_length=200)),
                ('item', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('category_source', models.CharField(choices=[('manual', '手動'), ('zaim', 'Zaim'), ('rule', 'ルール'), ('none', '未分類')], default='none', max_length=8)),
                ('kind', models.CharField(blank=True, max_length=10)),
                ('necessity', models.CharField(blank=True, max_length=10)),
                ('match_status', models.CharField(blank=True, choices=[('matched', '両方'), ('zaim_only', 'Zaimのみ'), ('enavi_only', 'e-naviのみ'), ('', '—')], max_length=12)),
                ('enavi_pay_method', models.CharField(blank=True, max_length=20)),
                ('enavi_is_installment', models.BooleanField(default=False)),
                ('row_type', models.CharField(default='normal', max_length=10)),
                ('exclude_reason', models.CharField(blank=True, db_index=True, max_length=24)),
                ('in_total', models.BooleanField(db_index=True, default=True)),
                ('dup_flag', models.CharField(blank=True, max_length=16)),
                ('manual_category', models.CharField(blank=True, max_length=50)),
                ('manual_subcategory', models.CharField(blank=True, max_length=50)),
                ('manual_necessity', models.CharField(blank=True, max_length=10)),
                ('exclude_override', models.BooleanField(blank=True, help_text='True=強制的に集計に含める / False=強制除外 / 未設定=自動判定', null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['ym', 'source_kind'], name='spending_tr_ym_599aa9_idx'), models.Index(fields=['-date', 'merchant'], name='spending_tr_date_9f3381_idx')],
            },
        ),
    ]
