# Generated by Django 5.2.16 on 2026-09-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=40)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('item_total', models.IntegerField(default=0, help_text='この商品の小計（円）')),
                ('order_total', models.IntegerField(default=0, help_text='注文全体の合計（円）')),
                ('status', models.CharField(blank=True, max_length=40)),
                ('source_file', models.CharField(blank=True, max_length=200)),
                ('match_how', models.CharField(blank=True, choices=[('charge', 'クレカ請求額で一致'), ('order', '注文合計で一致'), ('item', '商品小計で一致')], max_length=10)),
                ('transaction', models.ForeignKey(blank=True, help_text='対応するカード請求。突合できなければ空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_items', to='spending.transaction')),
            ],
            options={
                'ordering': ['-order_date', 'order_id'],
                'indexes': [models.Index(fields=['order_date'], name='spending_am_order_d_823884_idx')],
            },
        ),
    ]
