# Generated by Django 5.2.16 on 2026-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_amazonorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('amount', models.IntegerField(help_text='その月の手取り合計（円）')),
                ('source', models.CharField(choices=[('zaim', 'Zaimから取込'), ('manual', '手入力')], default='manual', max_length=8)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ym'],
                'constraints': [models.UniqueConstraint(fields=('ym', 'source'), name='uniq_income_ym_source')],
            },
        ),
    ]
