# Generated by Django 5.2.16 on 2026-09-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_monthlyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='label_clean',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='label_kind',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
