# Generated by Django 5.2.16 on 2026-09-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0005_transaction_label_clean_transaction_label_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, help_text='小さいほど先に評価する')),
                ('pattern', models.CharField(help_text='品目名に対する正規表現（部分一致）', max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
