# Generated by Django 5.2.16 on 2026-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0006_labelrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('item', models.CharField(help_text='Budget.category と同じ名前（家賃・電気 など）', max_length=50)),
                ('amount', models.IntegerField(help_text='その月に払った額（円）')),
                ('note', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ym', 'item'],
                'constraints': [models.UniqueConstraint(fields=('ym', 'item'), name='uniq_fixedcost_ym_item')],
            },
        ),
    ]
