# Generated by Django 5.2.16 on 2026-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0007_fixedcostentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ideal', models.IntegerField(help_text='理想の月額（円）')),
                ('order', models.IntegerField(default=100, help_text='並び順（小さいほど先）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-ideal', 'name'],
            },
        ),
    ]
