# Generated by Django 5.2.16 on 2026-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0008_templateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_debit_day', models.IntegerField(default=27, help_text='カードの引き落とし日（楽天=27）')),
                ('salary_day', models.IntegerField(default=25, help_text='給与日（累計を切る目印）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='templateitem',
            name='debit_day',
            field=models.IntegerField(blank=True, help_text='引き落とし日 1〜31（月末=31）', null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='via_card',
            field=models.BooleanField(default=False, help_text='カード払い（カードの引き落とし日にまとめる）'),
        ),
    ]
