# Generated by Django 5.2.16 on 2026-09-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0009_spendingsetting_templateitem_debit_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyincome',
            name='source',
            field=models.CharField(choices=[('zaim', 'Zaimから取込'), ('bank', '銀行明細から取込'), ('manual', '手入力')], default='manual', max_length=8),
        ),
    ]
