# Generated by Django 5.2.16 on 2026-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0010_alter_monthlyincome_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('manual', '手動'), ('zaim', 'Zaim'), ('rule', 'ルール'), ('fix', '品目ルール'), ('bank', '銀行明細'), ('none', '未分類')], default='none', max_length=8),
        ),
    ]
