# Generated by Django 5.2.16 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0011_alter_transaction_category_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingsetting',
            name='monthly_target',
            field=models.IntegerField(blank=True, help_text='月の目標支出額（円）。空なら平常月を代用', null=True),
        ),
    ]
