# Generated by Django 5.2.16 on 2026-09-04 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_totpdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='パスキー', help_text='どの端末か分かる名前（iPhone / 会社PC など）', max_length=60)),
                ('credential_id', models.CharField(db_index=True, help_text='base64url。ブラウザが返す鍵のID', max_length=400, unique=True)),
                ('public_key', models.TextField(help_text='base64url。検証にはこれだけを使う')),
                ('sign_count', models.BigIntegerField(default=0)),
                ('transports', models.CharField(blank=True, help_text='internal / hybrid など。QRログインの可否判定用', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
    ]
