# Generated by Django 5.2.16 on 2026-07-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('japan_kabu', '0005_alter_financialreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_code', models.CharField(blank=True, max_length=5)),
                ('recorded_at', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(choices=[('buy', '買い'), ('sell', '売り'), ('pass', '見送り')], max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('mood', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField()),
                ('impression', models.TextField(blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('review_result', models.CharField(blank=True, choices=[('success', '成功'), ('failure', '失敗'), ('lesson', '学びあり')], max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
