# Generated by Django 5.2.16 on 2026-07-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
