# Generated by Django 5.2.16 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='stop_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
