# Generated by Django 5.2.16 on 2026-09-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_stop_price_diaryentry_target_price'),
        ('japan_kabu', '0010_indexprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.IntegerField(default=1000000, help_text='資金全体（円）。1〜2%ルールの分母')),
                ('risk_pct', models.FloatField(default=2.0, help_text='1回の損失の上限（資金の%）')),
                ('default_stop_pct', models.FloatField(default=5.0, help_text='損切り幅の既定（%）')),
                ('default_target_pct', models.FloatField(default=10.0, help_text='利確幅の既定（%）')),
                ('cost_pct', models.FloatField(default=0.3, help_text='片道の手数料・スリッページ（%）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='strategy',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('strategy', models.CharField(choices=[('contra', '逆張り'), ('long', '長期'), ('div', '配当')], default='contra', max_length=10)),
                ('entry_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('shares', models.IntegerField()),
                ('stop_pct', models.FloatField()),
                ('target_pct', models.FloatField()),
                ('stop_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('entry_note', models.TextField(blank=True)),
                ('fx_at_entry', models.FloatField(blank=True, null=True)),
                ('risk_jpy', models.FloatField(blank=True, null=True)),
                ('over_risk', models.BooleanField(default=False)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('stop', '損切り'), ('target', '利確'), ('manual', '裁量'), ('time', '期限')], max_length=10)),
                ('exit_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diary.diaryentry')),
                ('exit_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diary.diaryentry')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='diary.trade'),
        ),
        migrations.CreateModel(
            name='TradeBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='diary.trade')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('trade', 'date'), name='uniq_trade_bar')],
            },
        ),
    ]
