# Generated by Django 5.2.16 on 2026-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_trade_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasetting',
            name='capital',
            field=models.IntegerField(default=10000, help_text='資金全体（取引の通貨のまま。米国株ならドル）。1〜2%ルールの分母'),
        ),
        migrations.AlterField(
            model_name='contrasetting',
            name='cost_pct',
            field=models.FloatField(default=0.5, help_text='片道の手数料・スリッページ（%）。ユーザー指定 0.5'),
        ),
    ]
