# Generated by Django 5.2.16 on 2026-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_contra_defaults_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(choices=[('contra', '短期'), ('long', '長期'), ('div', '配当')], default='contra', max_length=10),
        ),
    ]
