# Generated by Django 5.2.16 on 2026-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_strategy_label_tanki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasetting',
            name='cost_pct',
            field=models.FloatField(default=0.132, help_text='片道の手数料（%）。moomoo ベーシック 税込 0.132%'),
        ),
    ]
