# Generated by Django 5.2.16 on 2026-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_cost_moomoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('stop', '損切り'), ('target', '利確'), ('early', '早期利確'), ('manual', '裁量'), ('time', '期限')], max_length=10),
        ),
    ]
