# Generated by Django 5.2.16 on 2026-09-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_exit_early'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasetting',
            name='kind',
            field=models.CharField(choices=[('contra', '短期'), ('practice', '練習')], default='contra', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(choices=[('contra', '短期'), ('practice', '練習'), ('long', '長期'), ('div', '配当')], default='contra', max_length=10),
        ),
        migrations.CreateModel(
            name='PracticeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('mood', models.CharField(blank=True, max_length=20)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_meta', to='diary.trade')),
            ],
        ),
    ]
