# Generated by Django 5.2.16 on 2026-09-09 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_reset_contrasetting_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exit_expected',
            field=models.CharField(blank=True, choices=[('expected', '想定内'), ('unexpected', '想定外')], max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_scenario',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=20)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diary.trade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
