# Generated by Django 5.2.16 on 2026-09-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_notes_risk_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradenote',
            name='kind',
            field=models.CharField(blank=True, choices=[('good', '好材料'), ('bad', '悪材料')], max_length=10),
        ),
    ]
