# Generated by Django 5.2.16 on 2026-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_note_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradenote',
            name='at_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradenote',
            name='kind',
            field=models.CharField(blank=True, choices=[('good', '好材料'), ('bad', '悪材料'), ('info', '情報')], max_length=10),
        ),
    ]
