# Generated by Django 5.2.16 on 2026-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_backfill_reason_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradenote',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
