# Generated by Django 5.2.16 on 2026-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='rule_followed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sell_kind',
            field=models.CharField(blank=True, choices=[('profit', '利益確定'), ('loss', '損切り')], max_length=10),
        ),
    ]
