# Generated by Django 5.2.16 on 2026-09-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_diaryentry_sell_kind_rule_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('success', '成功'), ('failure', '失敗'), ('lesson', '学びあり')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='diary.diaryentry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
