# Generated by Django 5.2.16 on 2026-09-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_diaryreview_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasetting',
            name='be_trigger_pct',
            field=models.FloatField(default=7.0, help_text='建値ストップの発動（%）。0で無効'),
        ),
        migrations.AddField(
            model_name='trade',
            name='be_moved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='be_trigger_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('stop', '損切り'), ('target', '利確'), ('early', '早期利確'), ('breakeven', '建値撤退'), ('manual', '裁量'), ('time', '期限')], max_length=10),
        ),
    ]
