# Generated by Django 5.2.16 on 2026-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0020_breakeven_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradenote',
            name='kind',
            field=models.CharField(blank=True, choices=[('feel', '心情'), ('good', '好材料'), ('bad', '悪材料'), ('info', '情報')], max_length=10),
        ),
    ]
