# Generated by Django 5.2.16 on 2026-09-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_tradenote_feel'),
        ('japan_kabu', '0014_financialreport_pretax'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_code', models.CharField(blank=True, max_length=20)),
                ('placed_at', models.DateTimeField()),
                ('session_date', models.DateField()),
                ('limit_price', models.FloatField()),
                ('shares', models.IntegerField()),
                ('target_price', models.FloatField(blank=True, null=True)),
                ('stop_price', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('track_contra', models.BooleanField(default=False)),
                ('track_target', models.FloatField(blank=True, null=True)),
                ('risk_scenario', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '指値中'), ('filled', '約定'), ('unfilled', '約定せず')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('bar_date', models.DateField(blank=True, null=True)),
                ('day_open', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('day_close', models.FloatField(blank=True, null=True)),
                ('after_n', models.IntegerField(default=0)),
                ('after_high', models.FloatField(blank=True, null=True)),
                ('after_high_date', models.DateField(blank=True, null=True)),
                ('after_low', models.FloatField(blank=True, null=True)),
                ('after_low_date', models.DateField(blank=True, null=True)),
                ('after_close', models.FloatField(blank=True, null=True)),
                ('after_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_orders', to='diary.diaryentry')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
    ]
