# Generated by Django 5.2.16 on 2026-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0022_limitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fib_dir',
            field=models.CharField(blank=True, choices=[('down', '下落波の戻り'), ('up', '上昇波の押し')], max_length=4),
        ),
        migrations.AddField(
            model_name='trade',
            name='fib_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fib_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
