# Generated by Django 5.2.16 on 2026-07-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('display_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(blank=True, max_length=30)),
                ('sector33', models.CharField(blank=True, max_length=40)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('shares_disc_date', models.DateField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('price_date', models.DateField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-market_cap'],
            },
        ),
    ]
