# Generated by Django 5.2.16 on 2026-07-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector17',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
