# Generated by Django 5.2.16 on 2026-07-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0002_stock_sector17'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('volume', models.BigIntegerField()),
                ('turnover', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_volumes', to='japan_kabu.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_dailyvolume_stock_date')],
            },
        ),
    ]
