# Generated by Django 5.2.16 on 2026-07-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0003_stock_volume_stock_volume_date_stock_volume_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_end', models.DateField()),
                ('disc_date', models.DateField()),
                ('sales', models.BigIntegerField(blank=True, null=True)),
                ('op', models.BigIntegerField(blank=True, null=True)),
                ('np', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('equity', models.BigIntegerField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
                ('div_ann', models.FloatField(blank=True, null=True)),
                ('nx_div_ann', models.FloatField(blank=True, null=True)),
                ('nx_np', models.BigIntegerField(blank=True, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['fy_end'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'fy_end'), name='uniq_report_stock_fyend')],
            },
        ),
    ]
