# Generated by Django 5.2.16 on 2026-07-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0004_financialreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['per_end']},
        ),
        migrations.RemoveConstraint(
            model_name='financialreport',
            name='uniq_report_stock_fyend',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='per_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='per_type',
            field=models.CharField(default='FY', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='financialreport',
            constraint=models.UniqueConstraint(fields=('stock', 'per_end'), name='uniq_report_stock_perend'),
        ),
    ]
