# Generated by Django 5.2.16 on 2026-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0005_alter_financialreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(choices=[('JP', '日本株'), ('US', '米国株')], db_index=True, default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='display_code',
            field=models.CharField(max_length=12),
        ),
    ]
