# Generated by Django 5.2.16 on 2026-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0007_dailyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
