# Generated by Django 5.2.16 on 2026-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0008_stock_change_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('series', 'date'), name='uniq_macro_series_date')],
            },
        ),
    ]
