# Generated by Django 5.2.16 on 2026-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0009_macroindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_indexprice_symbol_date')],
            },
        ),
    ]
