# Generated by Django 5.2.16 on 2026-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0010_indexprice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialreport',
            name='uniq_report_stock_perend',
        ),
        migrations.AddConstraint(
            model_name='financialreport',
            constraint=models.UniqueConstraint(fields=('stock', 'per_end', 'per_type'), name='uniq_report_stock_perend_type'),
        ),
    ]
