# Generated by Django 5.2.16 on 2026-09-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0011_financialreport_unique_per_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='fin_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
