# Generated by Django 5.2.16 on 2026-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0012_financialreport_fin_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='source',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
