# Generated by Django 5.2.16 on 2026-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0013_financialreport_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='ordinary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='pretax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
