# Generated by Django 5.2.16 on 2026-08-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('japan_kabu', '0009_macroindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('stock_jp', models.FloatField(default=0)),
                ('stock_us', models.FloatField(default=0)),
                ('fund', models.FloatField(default=0)),
                ('metal', models.FloatField(default=0)),
                ('cash', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('principal', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('deposit', '入金'), ('withdraw', '出金')], max_length=10)),
                ('amount', models.FloatField()),
                ('memo', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_cash', models.FloatField(default=0)),
                ('baseline_cash_date', models.DateField(blank=True, null=True)),
                ('link_diary_to_cash', models.BooleanField(default=True)),
                ('alert_sector_pct', models.FloatField(default=30)),
                ('alert_top3_pct', models.FloatField(default=40)),
                ('alert_single_pct', models.FloatField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fund', '投資信託'), ('metal', '貴金属')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('assoc_fund_code', models.CharField(blank=True, max_length=16)),
                ('metal', models.CharField(blank=True, choices=[('gold', '金'), ('silver', '銀')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('stock', '個別株'), ('fund', '投資信託'), ('metal', '金・銀'), ('cash', '現金')], max_length=10, unique=True)),
                ('ratio', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='USDJPY', max_length=10)),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('pair', 'date'), name='uniq_fxrate_pair_date')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('avg_cost', models.FloatField()),
                ('baseline_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='japan_kabu.stock')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('stock__isnull', False)), models.Q(('product__isnull', False), ('stock__isnull', True)), _connector='OR'), name='holding_stock_xor_product'), models.UniqueConstraint(condition=models.Q(('stock__isnull', False)), fields=('stock',), name='uniq_holding_stock'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product',), name='uniq_holding_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.product')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', '-date'], name='portfolio_p_product_c09508_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='uniq_productprice_product_date')],
            },
        ),
    ]
