# Generated by Django 5.2.16 on 2026-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0009_macroindicator'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_stock',
        ),
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_product',
        ),
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('stock__isnull', False)), fields=('stock', 'account'), name='uniq_holding_stock_account'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'account'), name='uniq_holding_product_account'),
        ),
    ]
