# Generated by Django 5.2.16 on 2026-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0009_macroindicator'),
        ('portfolio', '0002_remove_holding_uniq_holding_stock_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_stock_account',
        ),
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_product_account',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='account',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_name',
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('stock__isnull', False)), fields=('stock',), name='uniq_holding_stock'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product',), name='uniq_holding_product'),
        ),
    ]
