# Generated by Django 5.2.16 on 2026-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0009_macroindicator'),
        ('portfolio', '0003_remove_holding_uniq_holding_stock_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_stock',
        ),
        migrations.RemoveConstraint(
            model_name='holding',
            name='uniq_holding_product',
        ),
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('積立投資枠', '積立投資枠'), ('成長投資枠', '成長投資枠')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('stock__isnull', False)), fields=('stock', 'account'), name='uniq_holding_stock_acct'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'account'), name='uniq_holding_product_acct'),
        ),
    ]
