# Generated by Django 5.2.16 on 2026-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_holding_uniq_holding_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosetting',
            name='link_diary_to_holdings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfoliosetting',
            name='link_diary_to_cash',
            field=models.BooleanField(default=False),
        ),
    ]
