# Generated by Django 5.2.16 on 2026-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfoliosetting_link_diary_to_holdings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('gold', '金'), ('silver', '銀'), ('platinum', 'プラチナ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='targetallocation',
            name='asset_class',
            field=models.CharField(choices=[('stock', '個別株'), ('fund', '投資信託'), ('metal', '貴金属'), ('cash', '現金')], max_length=10, unique=True),
        ),
    ]
