# Generated by Django 5.2.16 on 2026-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_product_metal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
