# Generated by Django 5.2.16 on 2026-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_holding_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='style',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('グロース', 'グロース'), ('大型', '大型'), ('配当狙い', '配当狙い'), ('バリュー', 'バリュー')], default='', max_length=20),
        ),
    ]
