# Generated by Django 5.2.16 on 2026-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_holding_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.TextField(blank=True, default='')),
                ('lessons', models.TextField(blank=True, default='')),
                ('cash_target', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
