# Generated by Django 5.2.16 on 2026-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_drillnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsnapshot',
            name='crypto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='crypto',
            field=models.CharField(blank=True, choices=[('btc', 'ビットコイン'), ('eth', 'イーサリアム'), ('xrp', 'XRP'), ('sol', 'ソラナ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fund', '投資信託'), ('metal', '貴金属'), ('crypto', '暗号資産')], max_length=10),
        ),
        migrations.AlterField(
            model_name='targetallocation',
            name='asset_class',
            field=models.CharField(choices=[('stock', '個別株'), ('fund', '投資信託'), ('metal', '貴金属'), ('crypto', '暗号資産'), ('cash', '現金')], max_length=10, unique=True),
        ),
    ]
