# Generated by Django 5.2.16 on 2026-09-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_kabu', '0013_financialreport_source'),
        ('portfolio', '0010_assetsnapshot_crypto_product_crypto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['stock_id', 'ex_date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'ex_date'), name='uniq_dividend_stock_ex')],
            },
        ),
    ]
