# Generated by Django 5.2.16 on 2026-09-26 22:05

from django.db import migrations, models
from django.db.models import F


def backfill(apps, schema_editor):
    # 既存の行は最後に保存した日時＝最後の棚卸し。登録画面で日記を見ながら数量を直した
    # 行（WU・1911・7013・9503）は、直す前の日記が二重に足されていたのがこれで解消する
    apps.get_model('portfolio', 'Holding').objects.update(baseline_at=F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_dividendrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='baseline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
