# Generated by Django 5.2.16 on 2026-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_holding_baseline_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('積立投資枠', '積立投資枠'), ('成長投資枠', '成長投資枠'), ('楽天', '楽天'), ('暗号', '暗号'), ('Moo', 'Moo'), ('SBI', 'SBI')], default='', max_length=20),
        ),
    ]
