# Generated by Django 5.2.16 on 2026-07-21 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('japan_kabu', '0006_stock_country_alter_stock_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_model', models.TextField(blank=True)),
                ('revenue_structure', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('competition', models.TextField(blank=True)),
                ('financial_policy', models.TextField(blank=True)),
                ('hypothesis', models.TextField(blank=True)),
                ('disconfirm', models.TextField(blank=True)),
                ('next_check', models.TextField(blank=True)),
                ('ir_url', models.URLField(blank=True, max_length=500)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karte', to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MidTermTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('target_fy', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='karte.stockkarte')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KpiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='karte.stockkarte')),
            ],
            options={
                'ordering': ['name', 'period'],
            },
        ),
    ]
