# Generated by Django 5.2.16 on 2026-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockkarte',
            name='mgmt_capital',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockkarte',
            name='mgmt_stance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockkarte',
            name='mgmt_track_record',
            field=models.TextField(blank=True),
        ),
    ]
