# Generated by Django 5.2.16 on 2026-07-21 00:47

import django.db.models.deletion
import karte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0002_stockkarte_mgmt_capital_stockkarte_mgmt_stance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=karte.models.executive_photo_path)),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='karte.stockkarte')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
