# Generated by Django 5.2.16 on 2026-07-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0003_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='title',
        ),
    ]
