# Generated by Django 5.2.16 on 2026-07-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0007_merge_invest_drop_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='karte.stockkarte')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
