# Generated by Django 5.2.16 on 2026-07-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0008_referencevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockkarte',
            name='memo',
        ),
    ]
