# Generated by Django 5.2.16 on 2026-07-21 23:27

import django.db.models.deletion
import karte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0009_remove_stockkarte_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=karte.models.screenshot_path)),
                ('note', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='karte.stockkarte')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
