# Generated by Django 5.2.16 on 2026-07-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0010_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockkarte',
            name='next_earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
