# Generated by Django 5.2.16 on 2026-07-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0011_stockkarte_next_earnings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencevideo',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
