# Generated by Django 5.2.16 on 2026-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0012_alter_referencevideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockkarte',
            name='section_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
