# Generated by Django 5.2.16 on 2026-09-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karte', '0013_stockkarte_section_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockkarte',
            options={'ordering': ['sort_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='stockkarte',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
