# Generated by Django 5.2.16 on 2026-09-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('japan_kabu', '0013_financialreport_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jpx400Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=20, verbose_name='業種（日経分類）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jpx400', to='japan_kabu.stock', verbose_name='銘柄')),
            ],
            options={
                'ordering': ['stock_id'],
            },
        ),
        migrations.CreateModel(
            name='KabutanBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabutan_bars', to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_kabutanbar_stock_date')],
            },
        ),
        migrations.CreateModel(
            name='ScreenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='判定日')),
                ('rule_version', models.CharField(default='v1.1', max_length=16, verbose_name='ルール版')),
                ('judgment', models.CharField(choices=[('BUY', 'BUY_CANDIDATE'), ('WAIT', 'WAIT'), ('NODATA', 'INSUFFICIENT_DATA')], max_length=8, verbose_name='判定')),
                ('met', models.JSONField(blank=True, default=list, verbose_name='成立した条件')),
                ('unmet', models.JSONField(blank=True, default=list, verbose_name='不成立の条件')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='判定日終値')),
                ('stop_price', models.FloatField(blank=True, null=True, verbose_name='損切り価格（直近10日安値）')),
                ('tp_price', models.FloatField(blank=True, null=True, verbose_name='利確目安（20日MA+10%）')),
                ('source', models.CharField(default='jpx400', max_length=8, verbose_name='ユニバース')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabutan_results', to='japan_kabu.stock')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'stock', 'rule_version'), name='uniq_screenresult_date_stock_rule')],
            },
        ),
    ]
