# Generated by Django 5.2.16 on 2026-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabutan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='開始')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='終了')),
                ('rule_version', models.CharField(default='v1.1', max_length=16)),
                ('bars_added', models.IntegerField(blank=True, null=True, verbose_name='追加した日足件数')),
                ('n_judged', models.IntegerField(default=0, verbose_name='判定銘柄数')),
                ('n_buy', models.IntegerField(default=0, verbose_name='BUY候補数')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='備考（取得失敗など）')),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
    ]
