"""
Django settings for web_kabuanalize project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 外部APIキー（config.json はコミットしないこと）
# 出所: Desktop/study/files/config.json（KABU_ANALIZE系スクリプトと共通のキー）
_CONFIG_PATH = BASE_DIR / 'config.json'
if _CONFIG_PATH.exists():
    with open(_CONFIG_PATH, encoding='utf-8') as f:
        _config = json.load(f)
else:
    _config = {}

JQUANTS_API_KEY = _config.get('api_key', '')   # J-Quants: "x-api-key" ヘッダーで使用
EDINET_API_KEY = _config.get('edinet_api_key', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tot_73$-4x))d5p^(g+1@t+=g$f-_omng=%un#ze)dhba-9u#c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'website',
    'japan_kabu',
    'diary',
    'karte',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_kabuanalize.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_kabuanalize.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# config.json に database 設定があればPostgreSQLを使う。
# 設定が無い場合、開発時(DEBUG=True)のみSQLiteにフォールバックする。
#
# 本番(DEBUG=False)で黙ってSQLiteに落ちると、空のDBが新規作成されて
# 「サイトは動くがデータが無い」という気付きにくい不整合になるため、
# ここで明示的に例外を投げて起動を止める。
if _config.get('database'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            **_config['database'],
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        'config.json の "database" 設定が見つかりません。\n'
        'config.json は .gitignore 対象のためリポジトリには含まれません。'
        'サーバーのプロジェクト直下に手動で設置してください（CLAUDE.md 参照）。'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# アップロードファイル（銘柄カルテの経営陣写真など）
# 本番では Web サーバー（nginx等）から /media/ を配信すること
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
