# Generated by Django 5.2.16 on 2026-09-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('earnings', '決算'), ('fomc', 'FOMC・金融政策'), ('macro', '経済指標'), ('politics', '政治・選挙'), ('dividend', '配当・権利'), ('other', 'その他')], default='earnings', max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('time_note', models.CharField(blank=True, max_length=20)),
                ('memo', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', '-important', 'category', 'id'],
            },
        ),
    ]
